### ISSUE TITLE
memory leaks: death

### ISSUE THREAD

**Issue by matthiaskrgr** [ReinhardPrix/FreedroidClassic#15]
when dying and terminating the game, I got these leaks
````
Direct leak of 127744 byte(s) in 16 object(s) allocated from:
    #0 0x31226a in __interceptor_calloc /home/matthias/LLVM/LLVM6/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97:3
    #1 0x3a41ec in MyMalloc /tmp/FreedroidClassic/src/misc.c:1077:15
    #2 0x38e159 in LoadShip /tmp/FreedroidClassic/src/map.c:287:30
    #3 0x375583 in InitNewMission /tmp/FreedroidClassic/src/init.c:696:8
    #4 0x38a069 in main /tmp/FreedroidClassic/src/main.c:86:7

Indirect leak of 6993 byte(s) in 217 object(s) allocated from:
    #0 0x31226a in __interceptor_calloc /home/matthias/LLVM/LLVM6/stage_2/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97:3
    #1 0x3a41ec in MyMalloc /tmp/FreedroidClassic/src/misc.c:1077:15
    #2 0x38e159 in LoadShip /tmp/FreedroidClassic/src/map.c:287:30
    #3 0x375583 in InitNewMission /tmp/FreedroidClassic/src/init.c:696:8
    #4 0x38a069 in main /tmp/FreedroidClassic/src/main.c:86:7
Indirect leak of 1520 byte(s) in 19 object(s) allocated from:
````

**Comment by ReinhardPrix** [comment]
Thanks, indeed there's tons of memory unfreed here, but this seems to be duplicate with #14, so I'm closing this one to keep things simpler.
