### ISSUE TITLE
crash: enabling decals && droid talk

### ISSUE THREAD

**Issue by matthiaskrgr** [ReinhardPrix/FreedroidClassic#26]
````rm ~/.freedroidClassic/config```` // reset config
menu -> legacy options 
now set ````Droid Talk```` yes
and ````Show Decals```` yes 
right after => boom

````
text.c:337:11: runtime error: load of null pointer of type 'char'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior text.c:337:11 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==7964==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000003c5214 bp 0x7ffea0aab330 sp 0x7ffea0aab200 T0)
==7964==The signal is caused by a READ memory access.
==7964==Hint: address points to the zero page.
    #0 0x3c5213 in DisplayText /tmp/FreedroidClassic/src/text.c:337:11
    #1 0x3ccd19 in PutInfluence /tmp/FreedroidClassic/src/view.c:356:7
    #2 0x3c9001 in Assemble_Combat_Picture /tmp/FreedroidClassic/src/view.c:224:2
    #3 0x3a0df6 in InitiateMenu /tmp/FreedroidClassic/src/menu.c
    #4 0x39d44d in handle_ShowDecals /tmp/FreedroidClassic/src/menu.c:340:7
    #5 0x3a31f5 in ShowMenu /tmp/FreedroidClassic/src/menu.c:901:13
    #6 0x3a320f in ShowMenu /tmp/FreedroidClassic/src/menu.c:906:13
    #7 0x3a278d in showMainMenu /tmp/FreedroidClassic/src/menu.c:695:3
    #8 0x37eac9 in ReactToSpecialKeys /tmp/FreedroidClassic/src/input.c:370:5
    #9 0x38ec47 in main /tmp/FreedroidClassic/src/main.c:125:4
    #10 0x7f31d9c92222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
    #11 0x27002d in _start (/tmp/FreedroidClassic/src/freedroid+0x27002d)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /tmp/FreedroidClassic/src/text.c:337:11 in DisplayText
==7964==ABORTING
````

**Comment by matthiaskrgr** [comment]
This bug also crashes the game right after starting when droid talk is enabled and the game is launched.

**Comment by ReinhardPrix** [comment]
heh, excellent, you seem to be really good at finding bugs  :) thanks!

I'll prioritize the issues according to relevance for my planned Android update in the play store (and that version fortunately doesn't feature the level editor, which I suspect will be the most work).
